baseURL = 'https://nereapf.github.io/hugo_portfolio'
languageCode = 'en-us'
title = 'Portfolio de Nerea'
theme = 'hugo-initio'

# Poner html en los md
[markup.goldmark.renderer]
  unsafe = true

# Sites Menus
[menu]
  [[menu.main]]
      name = "home"
      url = "/"
      weight = 1
  [[menu.main]]
      name = "pueblo"
      url = "/pueblo/"
      weight = 2
  [[menu.main]]
      name = "markdown"
      url = "/markdown/"
      weight = 3
  [[menu.main]]
      name = "televisión"
      url = "/television/"
      weight = 5
  [[menu.main]]
      name = "programación"
      url = "/programacion/"
      weight = 6

# Site Params
[params]
    showFooterFollowMe = true
    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownloads = true
    showClients = true
    avatar = "images/foto_dni.JPG"
    avatarclass = "circle"
    name = "Nerea Pellés Ferrer"
    description = "Alguna cosa sobre mí, sobre markdown, canales de televisión y mis estudios"
    phone = "640570979"
    email = "nereap492@gmail.com"
    address = "Zaragoza, España"
    year = 2024
    background = ""
    banner = "images/fondo.jpg"
    DateForm = "January 2, 2006"

    [[params.showFooterContact]]
    [[params.social]]
      name = "GitHub"
      url = "https://github.com/nereapf/"
      icon = "fab fa-github"
      footer = true

    [[params.social]]
      name = "Pinterest"
      url = "https://es.pinterest.com/nereapelles/"
      icon = "fab fa-pinterest"
      footer = true

    [[params.social]]
      name = "Google"
      url = "https://www.google.com/?hl=es"
      icon = "fab fa-google"
      footer = true

    [[params.showFooterTextWidget]]
    [[params.showFooterFormWidget]]